
name: build

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  push
    
env:
  ROM_URL: https://nbdlbuj2q0e3b95qd5q6djd9sscjt34t316crb1vpvs65nqr6qefv32p.qc.dolfincdnx.cn:10443/xdispatch1b9b48c974a31534/bigota.d.miui.com/V13.1.22.8.22.DEV/miui_ZEUS_V13.1.22.8.22.DEV_623e388db6_12.0.zip?bsreqid=670c7b1d6ed8b6ee2df817b26d3aa274
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main
           
       - name: Initialization environment
         run: |
            sudo apt install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/mi20210630/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              touch info.txt
              echo "By mi20210630 developed action" >>info.txt
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir upload
              zip -r GSI.zip ./*
              if [[ $(du -sb "GSI.zip" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.zip" | split -d -b 1024m - "upload/GSI.zip"
              else
                  mv GSI.zip upload/
              fi
              ls "upload"                  
              
       - name: Upload GSI to release
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}/ErfanGSIs/output/upload/*
           tag: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ github.run_number }}
           bodyFile: "info.txt"
           token: ${{ secrets.GITHUB_TOKEN }}
