name: build_ErfanGSIs

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://firmware.meizu.com/Firmware/Flyme/meizu18S_Pro/9.3.0.0/cn/20220812160612/9ee2f23c/update.zip
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai
  ARTIFACT_NAME: ErfanGSIs-test 

jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            brew install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd ErfanGSIs
              mkdir ./output
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd /ErfanGSIs
              mkdir upload
              sudo brew install p7zip 
              7z a -t7z -r ./upload/test.7z ./output/*
       
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: ${{ env.ARTIFACT_NAME }}
           path: |
                 "ErfanGSIs/output/*"
                 "ErfanGSIs/upload/test.7z*"
                 
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/upload
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./test.tar.gz

         
            
