name: system-test
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        run: |
          sudo apt install python3-pip
          python3 --version
          pip3 --version
          sudo apt install neofetch
          neofetch
  
