name: Darwin

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch
    
env:
  ROM_URL: https://media-gsjyg-person.gsjyoss.ctyunxs.cn/PERSONCLOUD/1b21fe23-b991-4898-8739-1d50f44de26a.7z?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=g6jU1T3TkAbPKf5ouH5d&x-amz-userLevel=0&x-amz-limitrate=51200&x-amz-UID=165559186197167&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22%E4%BC%A0%E9%9F%B3Tecno_Pova_3_LF7_HiOS8.6_12_aiduo_%E6%8F%90%E5%8F%96%E5%8E%9F%E5%8C%857z.7z%22%3Bfilename*%3DUTF-8%27%27%25E4%25BC%25A0%25E9%259F%25B3Tecno_Pova_3_LF7_HiOS8.6_12_aiduo_%25E6%258F%2590%25E5%258F%2596%25E5%258E%259F%25E5%258C%25857z.7z&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&Signature=zDa4PM0c8amALFfgdEwQHmq4edY%3D&x-amz-SHID=124121636213&Expires=1674561807&x-amz-FSIZE=2930930289&x-amz-UFID=21318116920908185
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo apt install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/mi20210630/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements with XiaoxinSGSI setup script
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir upload
              zip -r GSI.zip ./*
              if [[ $(du -sb "GSI.zip" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.zip" | split -d -b 1024m - "upload/GSI.zip"
              else
                  mv GSI.zip upload/
              fi
              ls "upload"                  
              
       - name: Upload SGSI to action-release...
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}/ErfanGSIs/output/upload/*
           tag: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ github.run_number }}
           bodyFile: "./ErfanGSIs/output/*.txt"
           token: ${{ secrets.GITHUB_TOKEN }}
