name: Darwin

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch
    
env:
  ROM_URL: https://downloads.sourceforge.net/project/jamie-roms/exthmui/exthm-10.0-20200721-UNOFFICIAL-SNAPSHOT-curtana.zip?ts=gAAAAABjz8WqlCjlG3ulpOPHCc8GVq8ISWzkwGlUSFaSgJLwRpZc28T9bnkAlf-4mf7ohOIxAe9o3s6PoCcG1V299vLkKgWViQ%3D%3D&use_mirror=master&r=
